version: '3.8'

x-service-base: &service-base
  init: true
  restart: unless-stopped
  environment:
    TZ: "Europe/Paris"

x-volume-base: &volume-base
  driver: local

services:
  db:
    <<: *service-base
    image: postgres:latest
    container_name: db
    env_file:
      - backend/app/.env
    networks:
      - endence

  backend:
    <<: *service-base
    depends_on:
      - db
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/app/.env
    volumes:
      - ./backend/app:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 5555:5555
    networks:
      - endence
  
  frontend:
    <<: *service-base
    container_name: front
    build: 
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/app:/app
      - /app/node_modules
    ports:
      - 3001:3000
    depends_on:
      - backend
    networks:
      - endence

  # adminer:
  #   <<: *service-base
  #   image: adminer
  #   container_name: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - endence

networks:
  endence:
    driver: bridge
    

