version: "3.8"

services:
  server:
    build:
      dockerfile: Dockerfile
      context: ../backend
    restart: unless-stopped
    volumes:
      - ../backend:/localghost/src/app
      - /localghost/src/app/node_modules
    ports:
      - 3001:3001

  chat:
    build:
      dockerfile: Dockerfile
      context: ./
    restart: unless-stopped
    volumes:
      - ./:/localghost/src/app
      - /localghost/src/app/node_modules/
    command: npm run start:dev
    depends_on:
      - postgres
    env_file: ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 3000:3000
      - 9239:9239

  front:
    build:
      dockerfile: Dockerfile
      context: ../front
    restart: unless-stopped
    volumes:
      - ../front:/app
      - /localghot/src/app/node_modules
    ports:
      - 4200:4200
    links:
      - chat

  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: db 
    ports:
      - 3500:5432

  postgres_admin:
    image: dpage/pgadmin4:7.6
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
