config:
  target: "http://172.17.0.2:3000"
  phases:
    - duration: 60
      arrivalRate: 20
      name: "Warming up"
    - duration: 240
      arrivalRate: 20
      rampTo: 100
      name: "Ramping up"
    - duration: 500
      arrivalRate: 100
      name: "Sustained load"
scenarios:
  - name: "Connecting to root"
    flow:
      - get:
          url: "/"